  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop Application User
      shell: /sbin/nologin
      system: true
      home: /app 

  - name: remove app directory if exists
    ansible.builtin.file:
      path: /app
      state: absent 

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete {{ component }} file if exists
    ansible.builtin.file:
      path: /tmp/{{ component }}.zip
      state: absent
  
  - name: download {{ component }} Application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
      dest: /tmp/{{ component }}.zip
    
  - name: extract {{ component }} Application
    ansible.builtin.unarchieve:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes


